# Generated by Django 3.2.6 on 2021-08-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brungasinc_app', '0002_auto_20210822_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
